codespell:config, workflow + typo fixes
bids-standard/bids-starter-kit pull request #293
Opened 2023-03-24 16:36 UTC by yarikoptic

TODO
- [ ] see if applicable to gh-pages -- might need to adjust workflow for that

2023-03-24 18:47 UTC, Remi-Gau requested changes
Thanks a bunch for taking care of that. 

Can you be a gem and also add it to the pre-commit config?

2023-03-24 21:35 UTC, yarikoptic commented
done, didn't test though yet.

2023-03-27 08:36 UTC, Remi-Gau commented
> done, didn't test though yet.

tested: it works

2023-03-27 08:36 UTC, Remi-Gau approved these changes

2023-03-27 08:36 UTC, merged